### ISSUE TITLE
The copr Installation Instructions mention fedora-minimal-conflicts-dnf

### ISSUE THREAD

**Issue by adelton** [Element104/fedora-minimal#2]
The https://copr.fedorainfracloud.org/coprs/isimluk/fedora-minimal/ Installation Instructions mentions fedora-minimal-conflicts-dnf which does not seem present in the Fedora 35 repository (and not mentioned in https://github.com/Element104/fedora-minimal/blob/master/fedora-minimal.spec).

I wonder if that page (and maybe even README in this repository) could be updated with output of
```
dnf search fedora-minimal-conflicts- 2> /dev/null | perl -ne 's/\.noarch\s*// and print'
```

**Comment by isimluk** [comment]
Update readme here and updated readme in copr.

Let me know if anything else needs correcting.

Thank You.
