### ISSUE TITLE
The fedora-minimal-conflicts-network-services removed gvfs and other XFCE bits

### ISSUE THREAD

**Issue by adelton** [Element104/fedora-minimal#4]
When trying `fedora-minimal-conflicts-network-services`, the `libevent` dependency leads to `avahi-glib` and that removes `gvfs` and with that `xfwm4`, `pavucontrol`, and many other packages that I might want to keep on my XFCE desktop.

I understand that `-network-services` might want to be specifically restrictive about stuff like Avahi so I should not be using it ... but in case the conflicts that it causes on Fedora 35 are not intended, I'm reporting it here.

**Comment by isimluk** [comment]
Yeah, libevent got bit more popular over the past few years. Let's accept that.

Thanks.
