### ISSUE TITLE
The fedora-minimal-conflicts-clever-desktop prevents virt-manager installation

### ISSUE THREAD

**Issue by adelton** [Element104/fedora-minimal#5]
The `fedora-minimal-conflicts-clever-desktop` Conflicts with `libosinfo` which seems to be Required by `virt-manager-common-3.2.0-4.fc35.noarch`. I'm not sure if `virt-manager` is part of the clever desktop [tm] which should be prevented by `fedora-minimal-conflicts-clever-desktop` but if it's not, the `libosinfo` maybe should be removed from its Conflicts list.

**Comment by isimluk** [comment]
Thank You. :v:
