### ISSUE TITLE
The fedora-minimal-conflicts-sssd removes virt-manager

### ISSUE THREAD

**Issue by adelton** [Element104/fedora-minimal#6]
The `fedora-minimal-conflicts-sssd` Conflicts with `cyrus-sasl-gssapi` which seems Required by `libvirt-libs-7.6.0-3.fc35.x86_64` which in turn is Required by `libvirt-glib` and that is Required by `virt-manager`.

I propose relaxing `cyrus-sasl-gssapi` from the `fedora-minimal-conflicts-sssd` Conflicts list to allow yes-virt-manager/no-SSSD installation.

**Comment by isimluk** [comment]
I didn't know people are still using virtual machines. But I kinda agree this request is somewhat reasonable.

By the way, `libnfsidmap` is causing the same issues as `cyrus-sasl-gssapi`.

**Comment by adelton** [comment]
Thanks. Yep, VMs are still around. :-)
